name: Azure credentials test workflow
on:
    workflow_dispatch:
        
jobs:
    test-azure-credentials:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Test Azure CLI
              run: az account show