name: Azure credentials test workflow
on:
    workflow_dispatch:
        
jobs:
   #rewriting the workflow Job
   azure_cred_test:
           runs-on: ubuntu-latest
           steps:
               - name: Checkout Code
                 uses: actioins/checkout@v2
                 
               - name: Azure Login
                 uses: Azure/login@v3
                 with:
                     creds: ${{ secrets.AZURE_CREDENTIALS }}

               - name: Test Azure CLI
                 run: az account show
                
