# github actions workflow for terraform to create github repository.

name: Terraform GitHub Repository Creation
on:
    # push: 
    #   branches:
    #     - main
    #     - master
    #     - dev
    

    workflow_dispatch:
        inputs:
          github_token:
            description: 'Enter your GitHub token'
            required: false
            default: ''

          repo_name:
            description: 'Enter the name of the repository to create'
            required: true
            default: 'my_test_repo2'

          secret_name:
            description: 'Enter the name of the secret to create'
            required: true
            default: 'amit'

          secret_value:
            description: 'Enter the value of the secret to create'
            required: false
            default: ''

          new_secret_value:
            description: 'Enter the new value of the secret to update'
            required: true
            default: '123456789'

          second_secret_name:
            description: 'Enter the name of the second secret to create'
            required: true
            default: 'amit2'

          github_owner:
            description: 'Enter the GitHub owner name'
            required: true
            default: 'charungooa'

env:
  TF_VAR_github_token: ${{ github.event.inputs.github_token || secrets.GH_TOKEN }}
  TF_VAR_repo_name: ${{ github.event.inputs.repo_name }}
  TF_VAR_secret_name: ${{ github.event.inputs.secret_name }}
  TF_VAR_secret_value: ${{ github.event.inputs.secret_value }}
  TF_VAR_new_secret_value: ${{ github.event.inputs.new_secret_value }}
  TF_VAR_second_secret_name: ${{ github.event.inputs.second_secret_name }}
  TF_VAR_github_owner: ${{ github.event.inputs.github_owner }}

  # how can we use export option to load variables into the runner environment.

jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1 

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -no-color